import { createFileRoute } from "@tanstack/react-router";
import { SiteLayout } from "@/components/site/SiteLayout";
import { AlertTriangle, ShieldCheck, HeartPulse, CheckCircle } from "lucide-react";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: "Disclaimer — ALORA" },
      { name: "description", content: "Important legal disclaimers regarding the capabilities, limits, and medical boundaries of ALORA's healthcare AI receptionist service." },
    ],
  }),
  component: Disclaimer,
});

function Disclaimer() {
  const lastUpdated = "June 2026";

  const boundaries = [
    {
      icon: <HeartPulse className="w-6 h-6 text-red-500" />,
      title: "No Medical Services",
      description: "ALORA is a medical answering tool. We do not diagnose, treat, or provide any clinical decision-making support."
    },
    {
      icon: <AlertTriangle className="w-6 h-6 text-amber-500" />,
      title: "Emergency Routing",
      description: "ALORA is not a 911 dispatch or suicide helpline. Callers in immediate physical danger must dial 911 directly."
    },
    {
      icon: <ShieldCheck className="w-6 h-6 text-primary" />,
      title: "Practice Validation",
      description: "Clinics retain full responsibility for verifying all patient schedules, appointment bookings, and EHR updates."
    }
  ];

  const sections = [
    {
      id: "no-medical-relationship",
      title: "1. No Medical or Professional Advice",
      content: "The contents of the ALORA website, marketing materials, web portals, and the responses generated by our automated AI voice receptionists are provided for administrative and operational assistance only. The Service does not establish a patient-provider relationship, nor does it deliver professional medical advice, clinical diagnostics, clinical triage, or therapy. AI receptionist statements cannot substitute for professional medical decisions, advice, or care."
    },
    {
      id: "emergency-policy",
      title: "2. Emergency Triage & Triage Limitations",
      content: "ALORA is built to manage patient intake, schedule follow-ups, document call logs, and reply to practice FAQs. It is not an emergency response hotline. The AI receptionists are trained to screen calls and immediately direct any patient reporting severe symptoms (such as chest pain, severe shortness of breath, heavy bleeding, or sudden neurological impairments) to hang up and dial 911 or visit the nearest hospital emergency room. ALORA accepts no liability for delayed care or errors occurring if callers fail to follow these emergency notices."
    },
    {
      id: "ai-transcription",
      title: "3. Accuracy & AI Technology Limitations",
      content: "Our Service utilizes advanced natural language processing (NLP) and voice synthesis models. Although we consistently train and test our models to ensure maximum conversational accuracy, you acknowledge that AI technology is subject to unexpected variations, transcription anomalies, accents or background noise interference, and network latencies. The Clinic holds the ultimate responsibility for verifying appointment logs, patient requests, clinical notes, and routing notifications synced to the Practice Management System."
    },
    {
      id: "ehr-pms",
      title: "4. Third-Party Integrations & Software Outages",
      content: "ALORA integrates with external Electronic Health Records (EHR) and Practice Management Systems (PMS). ALORA holds no responsibility or liability for scheduled bookings or sync failures resulting from vendor API modifications, clinical server outages, or general network disruptions that impede real-time updates."
    },
    {
      id: "compliance",
      title: "5. HIPAA & Clinical Compliance Boundaries",
      content: "ALORA provides HIPAA-compliant cloud infrastructure and signs Business Associate Agreements (BAAs) with all partner practices. The Clinic, however, remains responsible for ensuring that its internal staff follow HIPAA compliance guidelines regarding caller security verification, credential sharing, and portal permissions."
    }
  ];

  return (
    <SiteLayout>
      {/* Hero Section */}
      <section className="pt-32 pb-16 grid-bg border-b border-border/50" style={{ background: "var(--gradient-hero)" }}>
        <div className="max-w-4xl mx-auto px-6 text-center">
          <p className="text-xs font-display font-semibold tracking-[0.3em] uppercase text-primary mb-4">Legal Boundaries</p>
          <h1 className="font-display font-extrabold text-4xl lg:text-5xl leading-tight mb-4">
            Legal <span className="text-gradient italic">Disclaimer</span>
          </h1>
          <p className="text-muted-foreground max-w-2xl mx-auto text-base lg:text-lg">
            Understand the professional boundaries, emergency limitations, and technology scopes of ALORA's AI receptionists.
          </p>
          <p className="text-xs text-muted-foreground mt-4">Last Updated: {lastUpdated}</p>
        </div>
      </section>

      {/* Overview Cards */}
      <section className="py-12 bg-secondary/20">
        <div className="max-w-5xl mx-auto px-6">
          <div className="grid md:grid-cols-3 gap-6">
            {boundaries.map((b, idx) => (
              <div key={idx} className="card-elevated rounded-2xl p-6 flex flex-col items-start gap-4">
                <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center">
                  {b.icon}
                </div>
                <div>
                  <h3 className="font-display font-bold text-lg mb-2">{b.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{b.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Details Section */}
      <section className="py-20">
        <div className="max-w-4xl mx-auto px-6">
          <div className="card-elevated rounded-3xl p-8 lg:p-12 space-y-12 leading-relaxed">
            {sections.map((sec) => (
              <div key={sec.id} className="space-y-4">
                <h2 className="font-display font-extrabold text-2xl border-b border-border/60 pb-3">{sec.title}</h2>
                {sec.content && <p className="text-muted-foreground text-sm lg:text-base">{sec.content}</p>}
              </div>
            ))}
          </div>
        </div>
      </section>
    </SiteLayout>
  );
}
